import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;

import java.io.File;
import java.io.IOException;

class IndexBuilder {
    public static void main(String[] args) throws IOException {
        File html = new File("C:\\Projects\\krabcode\\index.html");
        Document doc = Jsoup.parse(html, "utf-8");
        Element container = doc.getElementById("autogenerated");
        container.text(""); //clear any current content
        println(doc.toString());

        /*TODO list folders and files
        // for each folder - if there is only 1 unique filename - create a simple modal div
        //                 - if there are more filenames - create a carousel with each filename
        //                 - upload to forpsi
         */
    }



    static void println(String line){
        System.out.println(line);
    }
}