import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;

import java.io.File;
import java.io.IOException;

class IndexBuilder {
    public static void main(String[] args) throws IOException {
        File html = new File("C:\\Projects\\krabcode\\index.html");
        Document doc = Jsoup.parse(html, "utf-8");
        println(doc.getElementById("autogenerated").toString());
    }

    static void println(String line){
        System.out.println(line);
    }
}